### ISSUE TITLE
Create meaningful obstacle positions for G1 and G2

### ISSUE THREAD

**Issue by darkobozhinoski** [rosin-project/metacontrol_experiments#11]
For the Baseline, it is needed for the local planner to not be able to find a path to the goal in one of the scenarios. 
That means the obstacles for G1 should be positioned as follows:
```
O1:
  pose:
    position:
      x: -5.5   (modified)
      y: 6.7  (modified)
      z: 0.0
  
O2:
  pose:
    position:
      x: -5.5    (modified)
      y: 5.3   (modified)
      z: 0.0
    
O3:
  pose:
    position:
      x: -5.5   (modified)
      y: 6.0   (modified)
      z: 0.0
```

Regarding G2,  we make change only in positioning of O3.

```
O3:
  pose:
    position:
      x: -6.3 (modified)
      y: -7.7
      z: 0.0

```

**Comment by marioney** [comment]
Done in https://github.com/rosin-project/metacontrol_experiments/commit/34e352eb7082232ce97b7ef627c689882a0c7b6f

**Comment by darkobozhinoski** [comment]
@marioney , I am still testing this part.

**Comment by darkobozhinoski** [comment]
@marioney ,
Change in the values for G1:

```
O1:
  pose:
    position:
      x: -6.5
      y: 7.5
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
O2:
  pose:
    position:
      x: -4.3
      y: 6.8
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
O3:
  pose:
    position:
      x: -5.1
      y: 5.4
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
```
